name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ forgejo.head_ref || forgejo.run_number }}-${{ forgejo.actor }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6.0.2
      - uses: https://codeberg.org/mlugg/setup-zig@v2.2.0
      - run: zig build test
